title: Your website        
theme: monocol-theme              
author: ffuentes
license: CC-BY             
highlighter: rouge
baseurl: "/monocol-theme"
include: [_posts]
pagination:
  
  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true
  sort_field: 'date'
  sort_reverse: true
plugins:
    - jekyll-paginate-v2